#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By

# shellcheck disable=SC2154
apt-get update -y
apt-get install -y nginx

# Add custom HTTP header X-Served-By containing the hostname
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By \$HOSTNAME;/" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
