#!/usr/bin/env bash
#install and configure haproxy on a load_balancer
sudo apt-get update -y

sudo apt-get install haproxy -y

server_config=\
"
frontend balancer_http_in
        bind *:80
        mode http
        default_backend benson-backend

backend balancer-backend
        balance roundrobin
        server 7142-web-01 	54.158.136.212:80 check
        server 7142-web-02 	3.83.151.210:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart