#!/usr/bin/env bash
# Fixes Nginx configuration to make sure it listens on IPv4 port 80

# Replace/fix any non-standard port or commented listen directives with port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default 2>/dev/null || true
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default 2>/dev/null || true

# Ensure service nginx starts/restarts correctly
service nginx restart
