#!/usr/bin/env bash
# install Nginx to serve a custom web page

sudo apt-get update -y #update all system index file before installing Nginx
sudo apt-get install nginx -y # install nginx web service. it will run as a service 
sudo echo "Holberton School must be Waka's gavorite school on the ALU INTRANET!" > /var/www/html/index.html # writes index.html
sudo service nginx start # start the service
