#!/usr/bin/env bash
# Configure Nginx with a redirect

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Configure the default site
sudo sh -c "cat > /etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 200 'Holberton School';
    }
}
EOF"

# Test configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart