#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me with a 301 status code

apt-get update -y
apt-get install -y nginx

# Inject redirection block using pipe delimiters in sed
sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart